{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "55d98944-20a8-42bf-847f-1100f55de25f",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-05-12 12:18:22.548 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.548 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.551 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.552 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.552 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.553 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.554 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.555 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.555 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.556 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.557 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.557 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.558 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.559 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.559 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.560 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.560 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.560 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.561 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.561 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.561 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.562 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.562 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.562 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.563 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.575 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.576 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.576 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.577 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.578 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.578 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.585 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.585 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.586 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.586 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "/var/folders/2j/5b31c79n4cn95mk8fqttl01h0000gn/T/ipykernel_6894/2872381795.py:78: DeprecationWarning: \n",
      "folium_static is deprecated and will be removed in a future release, or\n",
      "simply replaced with with st_folium which always passes\n",
      "returned_objects=[] to the component.\n",
      "Please try using st_folium instead, and\n",
      "post an issue at https://github.com/randyzwitch/streamlit-folium/issues\n",
      "if you experience issues with st_folium.\n",
      "\n",
      "  folium_static(m)\n",
      "2025-05-12 12:18:22.598 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.599 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.599 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.600 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.600 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-12 12:18:22.600 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "DeltaGenerator()"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import folium\n",
    "from folium.plugins import HeatMap\n",
    "from streamlit_folium import folium_static\n",
    "from sklearn.linear_model import LinearRegression\n",
    "import joblib\n",
    "\n",
    "# Load data\n",
    "df = pd.read_csv(\"/Users/vandana/Documents/Vishwas/delhi_property_data.csv\")\n",
    "\n",
    "# Sidebar filters\n",
    "st.sidebar.title(\"Filter Properties\")\n",
    "location = st.sidebar.selectbox(\"Select Location\", sorted(df['Location'].unique()))\n",
    "bhk = st.sidebar.selectbox(\"Select BHK\", sorted(df['BHK'].unique()))\n",
    "ptype = st.sidebar.selectbox(\"Property Type\", sorted(df['Property_Type'].unique()))\n",
    "size = st.sidebar.slider(\"Size (sqft)\", 400, 3500, 1000, 100)\n",
    "\n",
    "# Prepare model\n",
    "df_model = pd.get_dummies(df, columns=['Location', 'Property_Type', 'Builder'], drop_first=True)\n",
    "X = df_model.drop(['Total_Price'], axis=1)\n",
    "y = df_model['Total_Price']\n",
    "model = LinearRegression().fit(X, y)\n",
    "\n",
    "# Create input for prediction\n",
    "input_dict = {\n",
    "    'BHK': bhk,\n",
    "    'Size_sqft': size,\n",
    "    'Price_per_sqft': int(df[df['Location'] == location]['Price_per_sqft'].mean()),\n",
    "    'Age_of_Property': int(df[df['Location'] == location]['Age_of_Property'].mean()),\n",
    "}\n",
    "for col in X.columns:\n",
    "    if col.startswith('Location_'):\n",
    "        input_dict[col] = 1 if col == f'Location_{location}' else 0\n",
    "    elif col.startswith('Property_Type_'):\n",
    "        input_dict[col] = 1 if col == f'Property_Type_{ptype}' else 0\n",
    "    elif col.startswith('Builder_'):\n",
    "        input_dict[col] = 0  # set to 0 as builder input is skipped for simplicity\n",
    "\n",
    "input_df = pd.DataFrame([input_dict])\n",
    "predicted_price = model.predict(input_df)[0]\n",
    "\n",
    "st.title(\"🏠 Delhi Property Finder & Price Predictor\")\n",
    "st.markdown(f\"### Estimated Price: 💰 ₹{int(predicted_price):,}\")\n",
    "\n",
    "# Display top 5 listings\n",
    "st.subheader(\"Top Matching Listings\")\n",
    "top_matches = df[(df['Location'] == location) &\n",
    "                 (df['BHK'] == bhk) &\n",
    "                 (df['Property_Type'] == ptype) &\n",
    "                 (df['Size_sqft'].between(size - 200, size + 200))]\n",
    "\n",
    "st.dataframe(top_matches[['Location', 'BHK', 'Size_sqft', 'Price_per_sqft', 'Total_Price', 'Property_Type']].head(5))\n",
    "\n",
    "# Heatmap of average prices\n",
    "st.subheader(\"🌍 Price Heatmap (Mock Coordinates)\")\n",
    "\n",
    "# Assign mock lat/lng for demonstration\n",
    "location_coords = {\n",
    "    'Saket': [28.5222, 77.2100],\n",
    "    'Dwarka': [28.5921, 77.0460],\n",
    "    'Rohini': [28.7500, 77.0500],\n",
    "    'Lajpat Nagar': [28.5677, 77.2433],\n",
    "    'Karol Bagh': [28.6519, 77.1909],\n",
    "    'Connaught Place': [28.6315, 77.2167],\n",
    "    'Nehru Place': [28.5487, 77.2513],\n",
    "    'Vasant Kunj': [28.5205, 77.1635]\n",
    "}\n",
    "\n",
    "avg_prices = df.groupby('Location')['Price_per_sqft'].mean().reset_index()\n",
    "avg_prices['lat'] = avg_prices['Location'].map(lambda x: location_coords[x][0])\n",
    "avg_prices['lon'] = avg_prices['Location'].map(lambda x: location_coords[x][1])\n",
    "\n",
    "m = folium.Map(location=[28.61, 77.23], zoom_start=11)\n",
    "heat_data = [[row['lat'], row['lon'], row['Price_per_sqft']] for index, row in avg_prices.iterrows()]\n",
    "HeatMap(heat_data).add_to(m)\n",
    "folium_static(m)\n",
    "\n",
    "st.markdown(\"---\")\n",
    "st.markdown(\"Made with ❤️ for Delhi Real Estate\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
